[build]
  command = "npm install && npm uninstall @vitejs/plugin-react-swc && npm i @vitejs/plugin-react && npm i @esbuild/linux-x64 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.5"