[build]
  command = "npm install && npm uninstall @vitejs/plugin-react-swc && npm i @vitejs/plugin-react && npm i @esbuild/linux-x64 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.5"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"